# Generated by Django 4.2.5 on 2023-12-06 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="text",
        ),
    ]
